### ISSUE TITLE
Dynamic dashboard

### ISSUE THREAD

**Issue by pinhao** [Shopify/dashing#221]
I need to display ongoing events in a dashboard, I feel that a 1:1 relation between event and widget would be perfect.

I understand that dashing right now is more of a static dashboard with dynamic widgets, is there any way to create a dynamic dashboard with widgets that appear and disappear trough server sent events?

**Comment by CmdrCody** [comment]
I'm reviving this old thread, as I recently found myself implementing dashing for a project using highcharts and have been unable to turn anything up in the interwebs about this chicken-or-the-egg issue with initializing the charts. My highcharts charts work great once they're loaded with data, but if  users happen to hit the page before a send_event hits their client from the ruby job, they could be waiting until the next interval before they see anything.  

In my case, my data lives in Oracle, and I have my RB jobs are using OCI8 to retrieve the data and then building the various series objects for the different charts. I'm now facing the same problem as the OP, where my highcharts initialize as blank, since the series data comes from the server in the subsequentsend_event. 

I cannot figure out how to initialize the chart with some valid data from the first fetch. I've seen other posts around where people talk about "emiting" the series data in the DOM and then consuming it in the chart from the DOM on load; however, I can't figure out how to dynamically update the DOM from the Ruby Job. 

Has anyone figured a workaround for this? As it stands my charts are blank until the next 15-minute Send_Event. Obviously this won't work for my users, so I gotta figure something out.
