### ISSUE TITLE
Dashing with just the HTML and the CSS?

### ISSUE THREAD

**Issue by shuhaowu** [Shopify/dashing#223]
Is it possible to get a minimal setup with just the HTML, CSS, and some JavaScript? I don't need to fetch the events and what not.

The alternative would be specifying a set of server APIs that needs to be implemented for the client side app to use.

**Comment by amedhat3** [comment]
This also can be helpful
https://github.com/samaritanministries/dashing-css

**Comment by tylermauthe** [comment]
Is this still the idea for Dashing 2.0?

**Comment by tijszwinkels** [comment]
Thank you for the helpful pointers!

I needed this as well, so I spend some time picking Dashing apart. 

I created a new project on github. It's keeping everything nice and separated, and uses gulp and browserify to compile all the resources into something that can be uploaded to a webserver. Definitely a lot better than the giant blob of js, if I may say so myself. ;))

It's available here:
https://github.com/Iperity/Dashing-browser

**Comment by razb** [comment]
We already had a real-time  Express application utilizing websockets and didn't want to manage another messaging/events layer. We ended up integrating the Express app with dashing js  and using the existing primus library for both.

It was pretty straight forward. The clients connect to specific channels for each widget. As an example for the 'welcome'  text widget:

<pre>
primus = Primus.connect()
welcome = primus.channel('welcome')
welcome.on "data", (event) ->
   Dashing.widgets.welcome[0].receiveData event
</pre>

and the jobs on the server just need to use primus instead of batman:

<pre>
welcome.write({text: data });
</pre>

**Comment by RaresSalcudean** [comment]
@pushmatrix Thank you for the mini-dasbhoard repo, I was really looking for something like this. Is there any chance we can have the mini-dasbhoard without Batman.js? I'm really looking only for the basic dasbhoard with widgets, but no binding, only pure css html and js that is required to have the minimal functionality. Thank you!
