### ISSUE TITLE
Send multiple items to list widget

### ISSUE THREAD

**Issue by scabenga** [Shopify/dashing#405]
Hey there,

I wonder if it possible to send multiple items from different sources to the same widget?

An example of this would be using powershelll to send current CPU usage from multiple machine to one widget.

Many thanks

**Comment by tylermauthe** [comment]
There are two ways that I can think of to do this.

1) Add an onData handler to the list widget which updates the @items property of the widget instead of replacing it whole-hog.
2) Add some kind of middle-man which aggregates the results of the disparate sources into a single event that is sent to the dashboard.
