### ISSUE TITLE
Getting input from a form

### ISSUE THREAD

**Issue by paustindavis** [Shopify/dashing#453]
As part of a larger project.... I'm currently considering how I might get input from, probably from a form, within an active dashboard window and save the input to a file in dashing, preferably as json (though if I can capture the input I can figure it out from there).
For all you experts out there- is this even a viable idea? Any help simply pointing me in the right direction is appreciated.

**Comment by tylermauthe** [comment]
To me, the beauty of Dashing is the fact that you can define a Dashboard to be whatever you want. You aren't forced into a mould and you can create whatever crazy thing you can dream up.

As @cefigueiredo suggests, you can add custom routes for this. In your config.ru you can add routes:
```ruby
map Sinatra::Application.assets_prefix do
  run Sinatra::Application.sprockets
end

post '/custom/form' do
  puts params[:name]
end

run Sinatra::Application
```

You cannot really add routes like `/form`, as this will collide with Dashing's default dashboard route (`/:dashboard`).

Inside the route you can do whatever you want with the data -- which will be available in the params hash.

I would also suggest using a database instead of a file, even if you use SQLite. You may be able to store the data in memory too, if you do not require persistence. You can set a class variable in your config.ru (`@@variable`) and its state will be shared across requests.

**Comment by tylermauthe** [comment]
Please close this issue.
