### ISSUE TITLE
Different authentication settings for different dashboards in same app

### ISSUE THREAD

**Issue by pcavalheiro** [Shopify/dashing#458]
Possible to have different authentication settings for different dashboards? For example, I want to restrict access to a particular dashboard based on a username and password.

**Comment by tylermauthe** [comment]
In the protected! helper method of your config.ru you could switch on params[:dashboard] to run different auth code for different dashboards... Maybe. Let me know if that works!

**Comment by tylermauthe** [comment]
I have a cleaner solution for this, although it violates MVC so... Still kind of gross still.

Firstly, follow this:
https://github.com/Shopify/dashing/wiki/How-to:-Add-authentication

Except instead of calling the method protected! call it something else (maybe authenticate!)

Then inside your .erb file(s), you can just call it at the top: `<% authenticate! %>`

Maybe this is an indication that it would be nice to be able to mixin functionality to specific dashboard routes, but still have the standard dashing route execute after (or before).

**Comment by tylermauthe** [comment]
This issue can be closed.
