### ISSUE TITLE
iframe widget to display a local file

### ISSUE THREAD

**Issue by howardsternisbatman** [Shopify/dashing#468]
I thought I had this licked but nooooo

How can I have the iframe widget display a local html file located on the dashing server?

I've tried all sorts of variations of file://  file:/// etc.

curl -d '{"auth_token": "YOUR_AUTH_TOKEN", "url": "file:///administrator/manchvegas/xls/SFDC.html" }' \http://localhost:3030/widgets/iframe

I swear it worked for couple of moments then stopped after a reboot. I can curl an external website to display in the widget no problem.

If this isn't possible using iframe is there another approach I can make?

thanks

**Comment by tylermauthe** [comment]
The Dashing Client would need to be located on the same machine as the Dashing Server (otherwise the browser wouldn't be able to load the iFrame contents).

Otherwise, this should be possible:
http://stackoverflow.com/questions/11152103/displaying-local-htm-file-in-iframe

However, it sounds weird. If possible, put the HTML files into your Dashing app's public folder and reference them like this: (assuming: Dashing/public/SFDC.html)
```
    <li data-row="1" data-col="1" data-sizex="1" data-sizey="1">
      <div  data-id="iframe" data-url="/SFDC.html"></div>
    </li>
```
