### ISSUE TITLE
use .erb instead of .html in widget views

### ISSUE THREAD

**Issue by nicolnx** [Shopify/dashing#485]
Hi!

Just wondering is it possible to use ERB template engine instead of pure html widget views?
If not, maybe it is a good feture to implement in future?

Thanks
Nikolay

**Comment by tylermauthe** [comment]
You could send each peer to a different event ID (in my examples, "peer-#{peer.name}"). Then go back to using the data-foreach-peer approach, but make the ID of each element dynamic (like this: data-id="peer- | append peer.name").

You can also loop over your configuration data when dashing starts to run the Rufus jobs in parallel, so that the widgets would update independently.
