### ISSUE TITLE
Run Job at startup

### ISSUE THREAD

**Issue by aaldrich** [Shopify/dashing#50]
I have a Scheduler job that pulls some data from an external source and then sends it to the widget. How can I force that job to run whenever the page is refreshed? The contents don't change that frequently so I only want the job to run daily however whenever someone loads the dashboard for the first time I would like for it to load the contents. Here is my code:

Scheduler Job

require 'json'
require './lib/githubcomments'

comments = GithubComments.new

SCHEDULER.every '1d', :first_in => 0 do |job|
  points = [name: "Operations", data: [comments.january.count,comments.february.count,comments.march.count,comments.april.count,comments.may.count,comments.june.count,comments.july.count,comments.august.count,comments.september.count,comments.october.count,comments.november.count,comments.december.count]]
  x_axis = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
  y_axis_text = "Num of Comments"

  send_event('code_comments', {series: points, x_axis: x_axis, y_axis: y_axis_text})
end

Widget

class Dashing.Highchart extends Dashing.Widget
  createChart: (series,x_axis,y_axis) -> 
    @chart = new Highcharts.Chart
      chart:
        renderTo: "HCcontainer"
        type: "line"

```
  series: series 
  xAxis: {
    categories: x_axis
  }
  yAxis: {
    title: {
      text: y_axis
    }
  }
  plotOptions: {
    line: {
      dataLabels: {
        enabled: true
      }
    }
  }
```

  ready: ->
    series = []
    x_axis = []
    y_axis = ""
    @createChart(series,x_axis,y_axis)

  onData: (data) ->
    @createChart(data.series,data.x_axis,data.y_axis)

**Comment by CmdrCody** [comment]
I'm reviving this old thread, as I recently found myself implementing dashing for a project using highcharts and have been unable to turn anything up in the interwebs about this chicken-or-the-egg issue with initializing the charts. My highcharts charts work great once they're loaded with data, but if users happen to hit the page before a send_event hits their client from the ruby job, they could be waiting until the next interval before they see anything.

In my case, my data lives in Oracle, and I have my RB jobs are using OCI8 to retrieve the data and then building the various series objects for the different charts. I'm now facing the same problem as the OP, where my highcharts initialize as blank, since the series data comes from the server in the subsequentsend_event.

I cannot figure out how to initialize the chart with some valid data from the first fetch. I've seen other posts around where people talk about "emiting" the series data in the DOM and then consuming it in the chart from the DOM on load; however, I can't figure out how to dynamically update the DOM from the Ruby Job.

Has anyone figured a workaround for this? As it stands my charts are blank until the next 15-minute Send_Event. Obviously this won't work for my users, so I gotta figure something out.

**Comment by chrisspang** [comment]
Also just stumbled across this thread - the issue for me seems to be that 'onData' is fired before 'ready'.  I'm currently using a work-around that:

1. First call to onData() (with the old data) does create the (d3) svg successfully, but this gets lost (DOM not ready or something - I'm new to this stuff)
2. First call to ready() just calls onData()
3. onData() uses the stored values (@get("value")) to build the visualiation

 Untested rough example below:
```
  ready: ->
    @onData({ value: 0 })

  onData: (dataFull) ->
    data = dataFull.value    
    if (!data)
      data = @get("value")
     
    if (!data)
      return
```

**Comment by oaknguyen** [comment]
thanks for the work around @chrisspang.  Worked nicely.
