### ISSUE TITLE
Are there any UI developed on top of dashing?

### ISSUE THREAD

**Issue by kitex** [Shopify/dashing#590]
Are there any UI to develop dashboard?

**Comment by tylermauthe** [comment]
Not that I am aware of.

In order to be fully customizable, the backend is always written in (ruby) code. This is core to the philosophy of Dashing. It could certainly be a gem to extend Dashing, that'd be cool...

There are seceral cloud based alternatives with pre-baked integrations and nice UI to simplify things.

**Comment by tylermauthe** [comment]
Please close this issue. Support requests like this should be directed to Stack Overflow from now on.
