### ISSUE TITLE
HTML POST Form

### ISSUE THREAD

**Issue by charlievogt** [Shopify/dashing#705]
First of all, my apologies for being such an amateur.  Secondly, I'm struggling trying to make a form that a user can post text directly to a widget.  The code below results in an error.  Can anyone help me with a sample form written in HTML?

Thank you,
Charlie

```
<!DOCTYPE html>
<html>
<body>

<form action="http://dashboard:3030/widgets/text" method="post" enctype="text/plain" target="_self">
  <option value="tokenhere" name="auth_token"></option>
  Text: <input type="text" name="Text"><br>
  <input type="submit" value="Submit">
  
</form>

<p>Click submit, and watch this form fail miserably!</p>

</body>
</html>
```

> JSON::ParserError at /widgets/text
757: unexpected token at 'Text=sample'
file: common.rb location: parse line: 155

**Comment by pushmatrix** [comment]
Hey @charlievogt. These questions are better suited for Stack Overflow instead of as an issue here.

What you're running into is that Dashing expects data as JSON and not as plain form data. You'll need to use some javascript to turn the form data into valid JSON before sending it off
http://stackoverflow.com/questions/22195065/how-to-send-a-json-object-using-html-form-data
